### ISSUE TITLE
Installation error -  Illegal option

### ISSUE THREAD

**Issue by Rohlik** [hpcsc/aws-profile#17]
Hello,
I receive an error during the installation via cURL/script:
```
$ curl -sL https://raw.githubusercontent.com/hpcsc/aws-profile/master/install | sh
sh: 3: set: Illegal option -o pipefail
```

Environment:
OS Ubuntu 22.04
```
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by hpcsc** [comment]
sorry, I should have used `bash` instead of `sh` due to some bash-specific syntax in the installation script. Ubuntu by default links `sh` to `dash` instead of `bash`

if you try `curl -sL https://raw.githubusercontent.com/hpcsc/aws-profile/master/install | bash`, it should work
