### ISSUE TITLE
[Question] Rename it to aws-profile

### ISSUE THREAD

**Issue by boskiv** [hpcsc/aws-profile#2]
For me it's more convinient to run it with aws-profile only.
It's more humanable to type `aws-profile set/get` for me. 
What do you think ? 
Should I make PR for IT ?

**Comment by hpcsc** [comment]
It sounds good to me. Please feel free to submit a PR.

**Comment by hpcsc** [comment]
@boskiv the project is renamed to `aws-profile` as your suggestion
it now supports windows too
