### ISSUE TITLE
Region property support

### ISSUE THREAD

**Issue by dmitryax** [hpcsc/aws-profile#3]
Thank you for this very helpful tool.

What do you think about updating `defaut['region']` property with profile switching if it's set in `.aws/config`?

**Comment by hpcsc** [comment]
thanks. Glad that you find it useful

Updating `region` makes sense. I added that function in master branch (if you want to try it out, find binary with hash `6291f5f6f6ee45a875fbcf596bb98c89a5d50cdc` in https://dl.bintray.com/hpcsc/aws-profile/). I'll publish a new release in a few days after doing a few more changes

The logic at the moment is:

- if a profile in `credentials` is selected
   - if that profile has `region` set in `config` file, set `region` for `default` profile in `config` file
   - if that profile has no `region` setting, clear `region` in `default` profile in `config` file if have
- if a profile in `config` is selected
   - if that profile has `region` set, set `region` for `default` profile in `config` file
   - if that profile has no `region` setting, clear `region` in `default` profile in `config` file if have

Please let me know if you find any issue

**Comment by hpcsc** [comment]
released in v0.3.0

**Comment by dmitryax** [comment]
Great. It works. thank you!
